// <auto-generated />
namespace MyShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BasketMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasketMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201807182108142_BasketMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
